/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UsuarioDao;
import java.awt.Dimension;
import java.awt.Toolkit;
import model.UsuarioM;

/**
 *
 * @author joelmir
 */
public class Login extends javax.swing.JFrame {
    UsuarioDao Udao = new UsuarioDao() {};
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
         //Comando para centralizar janela
        // Obtém as dimensões da tela
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcula a posição para centralizar a janela
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

        // Define a posição da janela
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jdp_login = new javax.swing.JDesktopPane();
        jButton_Entrar = new javax.swing.JButton();
        jButton_sair = new javax.swing.JButton();
        jLabel_login = new javax.swing.JLabel();
        jLabel_senha = new javax.swing.JLabel();
        jPasswordField_senha = new javax.swing.JPasswordField();
        jTextField_usuario_login = new javax.swing.JTextField();
        jButton_CadastroUsuario_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jButton_Entrar.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton_Entrar.setText("Entrar");
        jButton_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EntrarActionPerformed(evt);
            }
        });

        jButton_sair.setText("Sair");
        jButton_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sairActionPerformed(evt);
            }
        });

        jLabel_login.setText("Login");

        jLabel_senha.setText("Senha");

        jButton_CadastroUsuario_.setText("Cadastro Usuario");
        jButton_CadastroUsuario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroUsuario_ActionPerformed(evt);
            }
        });

        jdp_login.setLayer(jButton_Entrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_login.setLayer(jButton_sair, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_login.setLayer(jLabel_login, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_login.setLayer(jLabel_senha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_login.setLayer(jPasswordField_senha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_login.setLayer(jTextField_usuario_login, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_login.setLayer(jButton_CadastroUsuario_, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdp_loginLayout = new javax.swing.GroupLayout(jdp_login);
        jdp_login.setLayout(jdp_loginLayout);
        jdp_loginLayout.setHorizontalGroup(
            jdp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_loginLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton_CadastroUsuario_, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jdp_loginLayout.createSequentialGroup()
                .addGroup(jdp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp_loginLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(jdp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jdp_loginLayout.createSequentialGroup()
                                .addComponent(jLabel_senha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPasswordField_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jdp_loginLayout.createSequentialGroup()
                                .addComponent(jLabel_login, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_usuario_login, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jdp_loginLayout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(jButton_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdp_loginLayout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(jButton_sair)))
                .addGap(30, 365, Short.MAX_VALUE))
        );
        jdp_loginLayout.setVerticalGroup(
            jdp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp_loginLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jdp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_usuario_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_login, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jdp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_senha))
                .addGap(40, 40, 40)
                .addComponent(jButton_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton_sair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jButton_CadastroUsuario_, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jdp_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EntrarActionPerformed
        UsuarioM u = this.Montarlogin();
        boolean tentativa=false;
        for( int i=1; i<3;i++){
            tentativa =  Udao.VerifLogin(u);
            if(tentativa = true){
                break;
            }
        }
        Limpar();
        this.dispose();
    }//GEN-LAST:event_jButton_EntrarActionPerformed

    private void jButton_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sairActionPerformed
         dispose();
    }//GEN-LAST:event_jButton_sairActionPerformed

    private void jButton_CadastroUsuario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroUsuario_ActionPerformed
        CadastroUsuarioLogin c = new CadastroUsuarioLogin();
        jdp_login.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jButton_CadastroUsuario_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    public void Limpar(){
        jTextField_usuario_login.setText("");
        jPasswordField_senha.setText("");
    }
    
     public UsuarioM Montarlogin(){
        UsuarioM Log = new UsuarioM();
        Log.setCpf(jTextField_usuario_login.getText());
        Log.setSenha(jPasswordField_senha.getText());
        return Log;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CadastroUsuario_;
    private javax.swing.JButton jButton_Entrar;
    private javax.swing.JButton jButton_sair;
    private javax.swing.JLabel jLabel_login;
    private javax.swing.JLabel jLabel_senha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_senha;
    private javax.swing.JTextField jTextField_usuario_login;
    private javax.swing.JDesktopPane jdp_login;
    // End of variables declaration//GEN-END:variables
}
