/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.AnimalM;
import model.ExameM;
import controller.AnimalDao;
import controller.ExameDao;
import controller.conn;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.FazendaM;

/**
 *
 * @author joelmir
 */
public class TelaPrincipal extends javax.swing.JFrame {
    AnimalDao Adao = new AnimalDao() {};
    ExameDao Edao = new ExameDao() {};
    
    int Buscar_V = -1;
    int Buscar_F = -1;
    int Buscar_A = -1;
    /**
     * Creates new form Principal
     */
    public TelaPrincipal() {
        initComponents();  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_principal_ = new javax.swing.JPanel();
        jdp_principal = new javax.swing.JDesktopPane();
        jButton_CadastrarExame_ = new javax.swing.JButton();
        jButton_fechar_ = new javax.swing.JButton();
        jLabel_TITULO = new javax.swing.JLabel();
        jLabel_dataNasc = new javax.swing.JLabel();
        jTextField_dataNascimento = new javax.swing.JTextField();
        jLabel_sexo = new javax.swing.JLabel();
        jTextField_sexoAnimal = new javax.swing.JTextField();
        jLabel_especie = new javax.swing.JLabel();
        jTextField_especie = new javax.swing.JTextField();
        jLabel_ExameAnimal = new javax.swing.JLabel();
        jLabel_tipoExame = new javax.swing.JLabel();
        jTextField_tipoExame = new javax.swing.JTextField();
        jLabel_resulExame = new javax.swing.JLabel();
        jTextField_ResultadoExame = new javax.swing.JTextField();
        jLabel_vascina = new javax.swing.JLabel();
        jTextField_Vascina = new javax.swing.JTextField();
        jLabel_peso = new javax.swing.JLabel();
        jTextField_Peso = new javax.swing.JTextField();
        jButton_BuscarFazenda_ = new javax.swing.JButton();
        jButton_BuscarVeterinario_ = new javax.swing.JButton();
        jLabel_descricaoAnimal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_DescricaoAnimal = new javax.swing.JTextArea();
        jLabel_dataPeso = new javax.swing.JLabel();
        jTextField_dataPeso = new javax.swing.JTextField();
        jLabel_dataVascina = new javax.swing.JLabel();
        jTextField_dataVascina = new javax.swing.JTextField();
        jLabel_CarFazenda = new javax.swing.JLabel();
        jButton_CadastrarAnimal_ = new javax.swing.JButton();
        jLabel_nome = new javax.swing.JLabel();
        jTextField_nomeAnimal = new javax.swing.JTextField();
        jButton_BuscarAnimal_ = new javax.swing.JButton();
        jButton_Limpar_ = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu_consultar = new javax.swing.JMenu();
        jMenuItem_ConsultarAnimal_ = new javax.swing.JMenuItem();
        jMenuItem_ConsultarExames_ = new javax.swing.JMenuItem();
        jMenuItem_ConsultarVeterinario_ = new javax.swing.JMenuItem();
        jMenuItem_ConsultarFazenda_ = new javax.swing.JMenuItem();
        jMenuItem_ConsultarUsuario_ = new javax.swing.JMenuItem();
        jMenu_Cadastrar_ = new javax.swing.JMenu();
        jMenuItem_CadastrarFazenda_ = new javax.swing.JMenuItem();
        jMenuItem_CadastrarVeterinario_ = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas Joelmir");
        setResizable(false);

        javax.swing.GroupLayout jPanel_principal_Layout = new javax.swing.GroupLayout(jPanel_principal_);
        jPanel_principal_.setLayout(jPanel_principal_Layout);
        jPanel_principal_Layout.setHorizontalGroup(
            jPanel_principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_principal_Layout.setVerticalGroup(
            jPanel_principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jdp_principal.setBackground(java.awt.SystemColor.activeCaption);
        jdp_principal.setForeground(new java.awt.Color(51, 51, 51));
        jdp_principal.setName(""); // NOI18N

        jButton_CadastrarExame_.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton_CadastrarExame_.setText("Cadastrar Exame");
        jButton_CadastrarExame_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastrarExame_ActionPerformed(evt);
            }
        });

        jButton_fechar_.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton_fechar_.setText("Fechar");
        jButton_fechar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fechar_ActionPerformed(evt);
            }
        });

        jLabel_TITULO.setText("INFORMAÇÕES DO ANIMAL:");

        jLabel_dataNasc.setText("Data Nascimento:");

        jLabel_sexo.setText("Sexo:");

        jLabel_especie.setText("Especie:");

        jLabel_ExameAnimal.setText("EXAMES DO ANIMAL:");

        jLabel_tipoExame.setText("Tipo Exame:");

        jLabel_resulExame.setText("Resultado Exame:");

        jLabel_vascina.setText("Vascina:");

        jLabel_peso.setText("Peso:");

        jButton_BuscarFazenda_.setText("Buscar Fazenda");
        jButton_BuscarFazenda_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarFazenda_ActionPerformed(evt);
            }
        });

        jButton_BuscarVeterinario_.setText("Buscar Veterinario");
        jButton_BuscarVeterinario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarVeterinario_ActionPerformed(evt);
            }
        });

        jLabel_descricaoAnimal.setText("Descrição Animal:");

        jTextArea_DescricaoAnimal.setColumns(20);
        jTextArea_DescricaoAnimal.setRows(5);
        jScrollPane1.setViewportView(jTextArea_DescricaoAnimal);

        jLabel_dataPeso.setText("Data Peso:");

        jLabel_dataVascina.setText("Data Vascina:");

        jLabel_CarFazenda.setText("(Digite Cadastro Ambiental Rural)");

        jButton_CadastrarAnimal_.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton_CadastrarAnimal_.setText("Cadastrar Animal");
        jButton_CadastrarAnimal_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastrarAnimal_ActionPerformed(evt);
            }
        });

        jLabel_nome.setText("Nome Animal:");

        jButton_BuscarAnimal_.setText("Buscar Animal");
        jButton_BuscarAnimal_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarAnimal_ActionPerformed(evt);
            }
        });

        jButton_Limpar_.setText("Limpar");
        jButton_Limpar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Limpar_ActionPerformed(evt);
            }
        });

        jdp_principal.setLayer(jButton_CadastrarExame_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_fechar_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_TITULO, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_dataNasc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_dataNascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_sexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_sexoAnimal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_especie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_especie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_ExameAnimal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_tipoExame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_tipoExame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_resulExame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_ResultadoExame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_vascina, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_Vascina, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_peso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_Peso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_BuscarFazenda_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_BuscarVeterinario_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_descricaoAnimal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_dataPeso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_dataPeso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_dataVascina, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_dataVascina, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_CarFazenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_CadastrarAnimal_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_nome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_nomeAnimal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_BuscarAnimal_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_Limpar_, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdp_principalLayout = new javax.swing.GroupLayout(jdp_principal);
        jdp_principal.setLayout(jdp_principalLayout);
        jdp_principalLayout.setHorizontalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_vascina)
                            .addComponent(jLabel_resulExame)
                            .addComponent(jLabel_tipoExame))
                        .addGap(48, 48, 48)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addComponent(jTextField_dataVascina, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_CadastrarExame_, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175))
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_ResultadoExame, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_tipoExame, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addComponent(jTextField_Vascina, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_fechar_, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jdp_principalLayout.createSequentialGroup()
                                        .addComponent(jTextField_dataPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(110, 110, 110)
                                        .addComponent(jButton_BuscarAnimal_, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(jButton_BuscarVeterinario_, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                                .addComponent(jButton_Limpar_)
                                .addGap(217, 217, 217))))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ExameAnimal)
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jdp_principalLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel_descricaoAnimal))
                                    .addComponent(jLabel_nome)
                                    .addComponent(jLabel_especie)
                                    .addComponent(jLabel_dataNasc)
                                    .addComponent(jLabel_dataPeso)
                                    .addComponent(jLabel_peso)
                                    .addComponent(jLabel_dataVascina))
                                .addGap(103, 103, 103)
                                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jdp_principalLayout.createSequentialGroup()
                                        .addComponent(jTextField_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100)
                                        .addComponent(jLabel_sexo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_sexoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField_especie, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jTextField_nomeAnimal)))
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel_CarFazenda)
                                .addGap(105, 105, 105)
                                .addComponent(jButton_BuscarFazenda_, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jButton_CadastrarAnimal_, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdp_principalLayout.setVerticalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel_TITULO)
                .addGap(24, 24, 24)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nome)
                    .addComponent(jTextField_nomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_especie)
                    .addComponent(jTextField_especie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_dataNasc)
                    .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_sexo)
                        .addComponent(jTextField_sexoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel_descricaoAnimal))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CarFazenda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_BuscarFazenda_))
                .addGap(42, 42, 42)
                .addComponent(jButton_CadastrarAnimal_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp_principalLayout.createSequentialGroup()
                        .addComponent(jLabel_ExameAnimal)
                        .addGap(18, 18, 18)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_tipoExame)
                            .addComponent(jTextField_tipoExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_resulExame)
                            .addComponent(jTextField_ResultadoExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Vascina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_vascina))
                        .addGap(27, 27, 27)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_dataVascina)
                            .addComponent(jTextField_dataVascina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp_principalLayout.createSequentialGroup()
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_peso)
                            .addComponent(jTextField_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_dataPeso)
                                    .addComponent(jTextField_dataPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp_principalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_BuscarAnimal_)
                                    .addComponent(jButton_BuscarVeterinario_))
                                .addGap(24, 24, 24))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp_principalLayout.createSequentialGroup()
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_CadastrarExame_, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_fechar_))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Limpar_)
                        .addGap(36, 36, 36))))
        );

        jMenu_consultar.setText("Consultar");
        jMenu_consultar.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jMenu_consultar.setMaximumSize(new java.awt.Dimension(150, 150));
        jMenu_consultar.setPreferredSize(new java.awt.Dimension(50, 50));

        jMenuItem_ConsultarAnimal_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_ConsultarAnimal_.setText("Animal");
        jMenuItem_ConsultarAnimal_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarAnimal_ActionPerformed(evt);
            }
        });
        jMenu_consultar.add(jMenuItem_ConsultarAnimal_);

        jMenuItem_ConsultarExames_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_ConsultarExames_.setText("Exames");
        jMenuItem_ConsultarExames_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarExames_ActionPerformed(evt);
            }
        });
        jMenu_consultar.add(jMenuItem_ConsultarExames_);

        jMenuItem_ConsultarVeterinario_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_ConsultarVeterinario_.setText("Veterinario");
        jMenuItem_ConsultarVeterinario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarVeterinario_ActionPerformed(evt);
            }
        });
        jMenu_consultar.add(jMenuItem_ConsultarVeterinario_);

        jMenuItem_ConsultarFazenda_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_ConsultarFazenda_.setText("Fazenda");
        jMenuItem_ConsultarFazenda_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarFazenda_ActionPerformed(evt);
            }
        });
        jMenu_consultar.add(jMenuItem_ConsultarFazenda_);

        jMenuItem_ConsultarUsuario_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_ConsultarUsuario_.setText("Usuario/Funcionario");
        jMenuItem_ConsultarUsuario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarUsuario_ActionPerformed(evt);
            }
        });
        jMenu_consultar.add(jMenuItem_ConsultarUsuario_);

        jMenuBar.add(jMenu_consultar);

        jMenu_Cadastrar_.setText("Cadastrar");
        jMenu_Cadastrar_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N

        jMenuItem_CadastrarFazenda_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_CadastrarFazenda_.setText("Fazenda");
        jMenuItem_CadastrarFazenda_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadastrarFazenda_ActionPerformed(evt);
            }
        });
        jMenu_Cadastrar_.add(jMenuItem_CadastrarFazenda_);

        jMenuItem_CadastrarVeterinario_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_CadastrarVeterinario_.setText("Veterinario");
        jMenuItem_CadastrarVeterinario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadastrarVeterinario_ActionPerformed(evt);
            }
        });
        jMenu_Cadastrar_.add(jMenuItem_CadastrarVeterinario_);

        jMenuBar.add(jMenu_Cadastrar_);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_principal_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdp_principal))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdp_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_principal_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_CadastrarFazenda_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastrarFazenda_ActionPerformed
        
        FazendaV f = new FazendaV();
        jdp_principal.add(f);
        f.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_CadastrarFazenda_ActionPerformed

    private void jMenuItem_CadastrarVeterinario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadastrarVeterinario_ActionPerformed
       
        Veterinario v = new Veterinario();
        jdp_principal.add(v);
        v.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_CadastrarVeterinario_ActionPerformed

    private void jMenuItem_ConsultarAnimal_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarAnimal_ActionPerformed
        
        ConsultarAnimal c = new ConsultarAnimal();
        jdp_principal.add(c);
        c.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_ConsultarAnimal_ActionPerformed

    private void jMenuItem_ConsultarExames_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarExames_ActionPerformed
        
       ConsultarExame ce = new ConsultarExame();
       jdp_principal.add(ce);
       ce.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_ConsultarExames_ActionPerformed

    private void jMenuItem_ConsultarVeterinario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarVeterinario_ActionPerformed
        
        ConsultarVeterinario cv = new ConsultarVeterinario();
        jdp_principal.add(cv);
        cv.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_ConsultarVeterinario_ActionPerformed

    private void jMenuItem_ConsultarFazenda_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarFazenda_ActionPerformed
        
        ConsultarFazenda cf = new ConsultarFazenda();
        jdp_principal.add(cf);
        cf.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_ConsultarFazenda_ActionPerformed

    private void jMenuItem_ConsultarUsuario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarUsuario_ActionPerformed
        
        ConsultarUsuario cu = new ConsultarUsuario();
        jdp_principal.add(cu);
        cu.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_ConsultarUsuario_ActionPerformed

    private void jButton_CadastrarAnimal_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastrarAnimal_ActionPerformed

        AnimalM a = this.CriarAnimal();
        Adao.inserir(a);
        
        Limpar();

    }//GEN-LAST:event_jButton_CadastrarAnimal_ActionPerformed

    private void jButton_BuscarVeterinario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarVeterinario_ActionPerformed

        String CPF = JOptionPane.showInputDialog("Informe o CPF");
        String sqlId = "SELECT idveterinario FROM Veterinario WHERE cpf = ?";
        
        try {
            PreparedStatement ps = conn.getConexao().prepareStatement(sqlId);
            ps.setString(1, CPF);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                Buscar_V = rs.getInt("idveterinario");
                JOptionPane.showMessageDialog(null, "Busca Confirmada ");
            }else{
                JOptionPane.showMessageDialog(null, "Veterinario Não Cadastrado! ");
            }
            
            ps.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro SQL: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton_BuscarVeterinario_ActionPerformed

    private void jButton_fechar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fechar_ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_fechar_ActionPerformed

    private void jButton_CadastrarExame_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastrarExame_ActionPerformed
        
        ExameM e = this.MontarExame();
        Edao.inserir(e);
        
        Limpar();
        
    }//GEN-LAST:event_jButton_CadastrarExame_ActionPerformed

    private void jButton_BuscarAnimal_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarAnimal_ActionPerformed
       
         String SQL = JOptionPane.showInputDialog("Informe o Nome Animal");
        String sqlId = "SELECT idanimal FROM Animal WHERE nomeanimal = ?";
        
        try {
            PreparedStatement ps = conn.getConexao().prepareStatement(sqlId);
            ps.setString(1, SQL);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                Buscar_A = rs.getInt("idanimal");
                JOptionPane.showMessageDialog(null, "Busca Confirmada ");
            }else{
                JOptionPane.showMessageDialog(null, "Animal Não Cadastrado! ");
            }
            
            ps.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro SQL: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton_BuscarAnimal_ActionPerformed

    private void jButton_Limpar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Limpar_ActionPerformed
        
        Limpar();
    }//GEN-LAST:event_jButton_Limpar_ActionPerformed

    private void jButton_BuscarFazenda_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarFazenda_ActionPerformed

        String CAR = JOptionPane.showInputDialog("Informe o Cadastro Ambiental Rural(CAR)");
        String sqlId = "SELECT idfazenda FROM Fazenda WHERE car = ?";
        
        try {
            PreparedStatement ps = conn.getConexao().prepareStatement(sqlId);
            ps.setString(1, CAR);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                Buscar_F = rs.getInt("idfazenda");
                JOptionPane.showMessageDialog(null, "Busca Confirmada ");
            }else{
                JOptionPane.showMessageDialog(null, "Fazenda Não Cadastrado! ");
            }
            
            ps.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro SQL" + ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton_BuscarFazenda_ActionPerformed
    
    public void Limpar(){
       
        jTextField_nomeAnimal.setText("");
        jTextField_sexoAnimal.setText("");
        jTextField_especie.setText("");
        jTextField_dataNascimento.setText("");
        jTextArea_DescricaoAnimal.setText("");
        jTextField_tipoExame.setText("");
        jTextField_ResultadoExame.setText("");
        jTextField_Vascina.setText("");
        jTextField_dataVascina.setText("");
        jTextField_Peso.setText("");
        jTextField_dataPeso.setText("");
    }
    
    public AnimalM CriarAnimal(){
        AnimalM a = new AnimalM();
            a.setNomeAnimal(jTextField_nomeAnimal.getText());
            a.setEspecie(jTextField_especie.getText());
            a.setDataNas(jTextField_dataNascimento.getText());
            a.setSexo(jTextField_sexoAnimal.getText());
            a.setDescricaoAnimal(jTextArea_DescricaoAnimal.getText());
            a.setFazenda(Buscar_F);
            return a;
    }
       
    public ExameM MontarExame(){
        
        ExameM e = new ExameM();
        e.setTipoExame(jTextField_tipoExame.getText());
        e.setResulExame(jTextField_ResultadoExame.getText());
        e.setVacina(jTextField_Vascina.getText());
        e.setDataVacina(jTextField_dataVascina.getText());
        e.setPeso(jTextField_Peso.getText());
        e.setDataPeso(jTextField_dataPeso.getText());
        e.setVeterinario(Buscar_V);
        e.setAnimal(Buscar_A);
        return e;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_BuscarAnimal_;
    private javax.swing.JButton jButton_BuscarFazenda_;
    private javax.swing.JButton jButton_BuscarVeterinario_;
    private javax.swing.JButton jButton_CadastrarAnimal_;
    private javax.swing.JButton jButton_CadastrarExame_;
    private javax.swing.JButton jButton_Limpar_;
    private javax.swing.JButton jButton_fechar_;
    private javax.swing.JLabel jLabel_CarFazenda;
    private javax.swing.JLabel jLabel_ExameAnimal;
    private javax.swing.JLabel jLabel_TITULO;
    private javax.swing.JLabel jLabel_dataNasc;
    private javax.swing.JLabel jLabel_dataPeso;
    private javax.swing.JLabel jLabel_dataVascina;
    private javax.swing.JLabel jLabel_descricaoAnimal;
    private javax.swing.JLabel jLabel_especie;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_peso;
    private javax.swing.JLabel jLabel_resulExame;
    private javax.swing.JLabel jLabel_sexo;
    private javax.swing.JLabel jLabel_tipoExame;
    private javax.swing.JLabel jLabel_vascina;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem_CadastrarFazenda_;
    private javax.swing.JMenuItem jMenuItem_CadastrarVeterinario_;
    private javax.swing.JMenuItem jMenuItem_ConsultarAnimal_;
    private javax.swing.JMenuItem jMenuItem_ConsultarExames_;
    private javax.swing.JMenuItem jMenuItem_ConsultarFazenda_;
    private javax.swing.JMenuItem jMenuItem_ConsultarUsuario_;
    private javax.swing.JMenuItem jMenuItem_ConsultarVeterinario_;
    private javax.swing.JMenu jMenu_Cadastrar_;
    private javax.swing.JMenu jMenu_consultar;
    private javax.swing.JPanel jPanel_principal_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_DescricaoAnimal;
    private javax.swing.JTextField jTextField_Peso;
    private javax.swing.JTextField jTextField_ResultadoExame;
    private javax.swing.JTextField jTextField_Vascina;
    private javax.swing.JTextField jTextField_dataNascimento;
    private javax.swing.JTextField jTextField_dataPeso;
    private javax.swing.JTextField jTextField_dataVascina;
    private javax.swing.JTextField jTextField_especie;
    private javax.swing.JTextField jTextField_nomeAnimal;
    private javax.swing.JTextField jTextField_sexoAnimal;
    private javax.swing.JTextField jTextField_tipoExame;
    private javax.swing.JDesktopPane jdp_principal;
    // End of variables declaration//GEN-END:variables
}
